sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tF41nYPaeQRNbzPz9kh
    access-key-secret: qCwZJ6XbEOjp2ImT2T4rO2qCizMHqr
    bucket-name: gelato
  redis:
    host: localhost
    port: 6379
    database: 1
#  wechat:
#    appid: wxd41bb4b9cc0a44ff
#    secret: b66e6cd2588b894a3e0036abf4cf6767
  wechat:
    appid: wxd41bb4b9cc0a44ff
    secret: b66e6cd2588b894a3e0036abf4cf6767
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php